
bind = SUPER,       return, exec, $TERM
bind = SUPER SHIFT, return, exec, $TERM_APP
bind = SUPER,       slash, exec, $TERM -e $FM
bind = SUPER SHIFT, slash, exec, $TERM_APP launch -- $FM

bind = SUPER,       minus, exec, $TERM -e $AUDIO_CTRL
bind = SUPER,       equal, exec, $TERM -e $PROC_CTRL

bind = SUPER,       space, exec, wofi -S run

bind = SUPER,       backspace, exec, $BROWSER
bind = SUPER SHIFT, backspace, exec, nyxt

