
$TERM = kitty

bind=SUPER, tab, submap, project

submap=project

    bind=SUPER, tab, exec, $TERM -e project ide
    bind=SUPER, tab, submap, reset

    bind=SUPER, e, exec, $TERM -e project edit
    bind=SUPER, e, submap, reset

    bind=SUPER, grave, exec, project select
    bind=SUPER, grave, submap, reset

    bind=SUPER, slash, exec, project nav
    bind=SUPER, slash, submap, reset

    bind=SUPER, escape, submap, reset

submap=reset

