#!/bin/sh
ROOT=$HOME/untill/mlibs/static/

use gar-publish
use python-tooling

cmd_scss() {
    cd "$ROOT"
    arg=$1; [[ -n $1 ]] && shift
    case $arg in
        watch)
            target=$HOME/untill/portal/app/static/css/
            sass --load-path=style --watch style:$target
            ;;
    esac
}

cmd_sass() {
    cmd_scss $@
}
