#!/bin/sh
ROOT=$HOME/untill/mlibs/static/

cmd_publish() {
    cd "$ROOT"

    read -e -p "$(uv version) -> " version
    [[ -n $version ]] && uv version $version || version=$(uv version | cut -d' ' -f2)
    rm -rf dist/
    uv build --no-sources
    uv publish --index google
}

cmd_scss() {
    cd "$ROOT"
    arg=$1; [[ -n $1 ]] && shift
    case $arg in
        watch)
            target=$HOME/untill/portal/app/static/css/
            sass --load-path=style --watch style:$target
            ;;
    esac
}

cmd_sass() {
    cmd_scss $@
}
