#!/bin/sh
#
# We will use `stow` to 
# Requirements:
#   GNU Stow (https://www.gnu.org/software/stow/)
#     For linking `.qore` files elsewhere in your home directory
#

# Exit on error
set -e

# Ensure we are in this script's directory, `.qore`'s project home.
cd "$(dirname "$0")"

# Capture the config home directory
configs=${XDG_CONFIG_HOME:-~/.config}
# Link global configs
stow -R --no-folding --override='.*' -t "$configs" config
# Link machine-specific configs, overriding global configs
machine=$(cat /etc/hostname 2>/dev/null || uname -n)
machine=${machine%%.*}
if [ -d "config.$machine" ]; then
    stow -R --no-folding --override='.*' -t "$configs" "config.$machine"
fi
# Link shell dot files to the home directory from the config home
stow -R --ignore='^(mod|env\.d)$' -d "$configs" -t ~ shell
