#!/bin/sh

# project root directory
ROOT=$HOME/untill/ctrlnet
cd $ROOT

ARG=$1; shift
case $ARG in
    root) 
        pwd
    ;;
    ide)
        nvim
    ;;
    run)
        RUST_LOG=info cargo run
    ;;
    build)
        cargo build
    ;;
esac
