#!/bin/sh

# project root directory
ROOT=$HOME/untill/farmchain
cd $ROOT
source $ROOT/.env

ARG=$1; [[ -n $1 ]] && shift
case $ARG in
    path)
        pwd
    ;;
    root)
        pwd
    ;;
    ide)
        source venv/bin/activate
        nvim 
    ;;
    app)
        HOST=0.0.0.0
        PORT=5300
        ARG=$1; [[ -n $1 ]] && shift
        case $ARG in
            "")
                echo "app command not provided"
            ;;
            serve)
                SERVER_IMPLEMENTATION=uvicorn venv/bin/python -m uvicorn --host $HOST --port $PORT --reload app:app
            ;;
            *)   
                echo "'app ${ARG:-<null>}' command not configured"
            ;;
        esac 
    ;;
    pip)
        venv/bin/pip $*
        if [ "$1" == "install" ]; then
            venv/bin/pip freeze > requirements.txt
        fi
    ;;
    git)
        git $*
    ;;
esac
