#!/bin/sh

# project root directory
ROOT=$HOME/untill/farmflow
cd $ROOT

ARG=$1; [[ -n $1 ]] && shift
case $ARG in
    path) pwd ;;
    root) pwd ;;
    ide) nvim ;;
    app)
        HOST=0.0.0.0
        PORT=5100
        ARG=$1; [[ -n $1 ]] && shift
        case $ARG in
            "")
                echo "app command not provided"
            ;;
            serve)
                uv run uvicorn --host $HOST --port $PORT --reload --factory app:serve
            ;;
            *)   
                echo "'app ${ARG:-<null>}' command not configured"
            ;;
        esac 
    ;;
    sim)
        ARG=${1:-cli}; [[ -n $1 ]] && shift
        case $ARG in
            serve)
                uv run uvicorn --host 0.0.0.0 --port 5150 --reload tools.sim:sim
            ;;
            *)   
                echo "'sim ${ARG:-<null>}' command not configured"
            ;;
        esac 
    ;;
    *)
        echo "'${ARG:-<null>}' not configured"
    ;;
esac
