#!/bin/sh

# project root directory
ROOT=$HOME/projects/fractal
cd $ROOT

ARG=$1; [[ -n $ARG ]] && shift;
case $ARG in
    ide)
        nvim
    ;;
    build)
        cargo build $@
    ;;
    run)
        ARG=$1; [[ -n $ARG ]] && shift;
        case $ARG in
            reload)
                cargo watch -cx run $@
            ;;
            *)
                cargo run $ARG $@
            ;;
        esac
    ;;
    *) 
        pwd
    ;;
esac

