#!/bin/sh

# project root directory
ROOT=$HOME/untill/mlibs
cd $ROOT

ARG=$1
[[ -n $1 ]] && shift
case $ARG in
    root) 
        pwd
    ;;

    list)
        echo 'chem common db files inv notify security server static units'
    ;;

    ide)
        subproject=`mlibs list | sed 's/ /\'$'\n''/g' | wofi --dmenu`
        [[ -n $subproject ]] && mlibs $subproject ide 
    ;;

    chem)
        cd chem
        source venv/bin/activate
        ARG=$1
        [[ -n $1 ]] && shift
        case $ARG in
            ide)
                nvim
            ;;
        esac
    ;;

    common)
        cd common
        source venv/bin/activate
        ARG=$1
        [[ -n $1 ]] && shift
        case $ARG in
            ide)
                nvim
            ;;
        esac
    ;;

    db)
        cd db
        source venv/bin/activate
        ARG=$1
        [[ -n $1 ]] && shift
        case $ARG in
            ide)
                nvim
            ;;
        esac
    ;;

    files)
        cd files
        source venv/bin/activate
        ARG=$1
        [[ -n $1 ]] && shift
        case $ARG in
            ide)
                nvim
            ;;
        esac
    ;;

    inv)
        cd inv
        source venv/bin/activate
        ARG=$1
        [[ -n $1 ]] && shift
        case $ARG in
            ide)
                nvim
            ;;
        esac
    ;;

    notify)
        cd notify
        source venv/bin/activate
        ARG=$1
        [[ -n $1 ]] && shift
        case $ARG in
            ide)
                nvim
            ;;
        esac
    ;;

    security)
        cd security
        source venv/bin/activate
        case $ARG in
            ide)
                nvim
            ;;
        esac
    ;;

    server)
        cd server
        source venv/bin/activate
        ARG=$1
        [[ -n $1 ]] && shift
        case $ARG in
            ide)
                nvim
            ;;
        esac
    ;;

    static)
        cd static
        ARG=$1
        [[ -n $1 ]] && shift
        case $ARG in
            ide)
                nvim
            ;;
            style)
                MATIA_CSS=$HOME/untill/matia/app/static/css
                sass --load-path=style --watch style/:$MATIA_CSS/
            ;;
        esac
    ;;

    units)
        cd units
        source venv/bin/activate
        ARG=$1
        [[ -n $1 ]] && shift
        case $ARG in
            ide)
                nvim
            ;;
        esac
    ;;
    *)
        echo "Unhandled argument: $ARG"
esac
