#!/bin/sh

# project root directory
ROOT=$HOME/untill/portal
cd $ROOT

ARG=$1; [[ -n $1 ]] && shift
case $ARG in
    path) pwd ;;
    root) pwd ;;
    ide) nvim ;;
    app)
        HOST=0.0.0.0
        PORT=5000
        ARG=$1; [[ -n $1 ]] && shift
        case $ARG in
            "")
                echo "app command not provided"
            ;;
            serve)
                uv run uvicorn --host $HOST --port $PORT --reload --factory app:serve
            ;;
            *)   
                echo "'app ${ARG:-<null>}' command not configured"
            ;;
        esac 
    ;;
    *) echo "'${ARG:-<null>}' not configured" ;;
esac
