#!/bin/sh

# project root directory
ROOT=$HOME/projects/uv
cd $ROOT
source $ROOT/.env

ARG=$1; shift
case $ARG in
    path) pwd ;;
    root) pwd ;;
    ide)
        source venv/bin/activate
        nvim
    ;;
    run)
        venv/bin/python -m uvicorn \
            --host 0.0.0.0 \
            --port 8000 \
            --reload \
            app:app $@
    ;;
    pip)
        venv/bin/pip $*
        if [ "$1" == "install" ]; then
            venv/bin/pip freeze > requirements.txt
        fi
    ;;
esac
