#!/bin/sh
ROOT=$HOME/untill/matia

cmd_db() {
    cd "$ROOT/.mongo"
    source "../.env"
    URI="$MONGO_PROTOCOL://$MONGO_USER:$MONGO_PASS@$MONGO_HOST"
    VERB=${1:-sh}
    [[ -n $1 ]] && shift
    case $VERB in
        sh|shell)
            DB=${1:-development}
            [[ -n $1 ]] && shift
            mongosh $URI/$DB $@
        ;;
        dump)
            DB=${1:-development}
            [[ -n $1 ]] && shift
            COLLECTION=$1
            if [[ -n $COLLECTION ]]; then
                mongodump $URI -d $DB -c $COLLECTION
            else
                mongodump $URI -d $DB
            fi
        ;;
        restore)
            DB_IN=$1
            DB_OUT=$2
            COLLECTION=$3
            if [[ -n $COLLECTION ]]; then
                mongorestore $URI --drop --nsInclude="$DB_OUT.$COLLECTION"  dump/$DB_IN/$COLLECTION.bson
            else
                mongorestore $URI --drop --db=$DB_OUT dump/$DB_IN/
            fi 
        ;;
        migrate)
            DB_IN=$1
            DB_OUT=$2
            COLLECTION=$3
            matia db dump $DB_IN $COLLECTION
            matia db restore $DB_IN $DB_OUT $COLLECTION
        ;;
    esac 
}
