#!/bin/sh

ROOT=$HOME/untill/ctrlio

 cmd_app() {
     case "$1" in
         serve)
             cd "$ROOT"
             uv run uvicorn --reload --host 0.0.0.0 --port 5140 --factory app:serve
             ;;
     esac
 }
