#!/bin/sh

# Color vars for convenience
if [ -t 1 ]; then
    c_reset='[0m'
    c_bold='[1m'
    c_dim='[2m'
    c_green='[32m'
    c_yellow='[33m'
else
    c_reset='' c_bold='' c_dim='' c_green='' c_yellow=''
fi

# Relative time formatting
_reltime() {
    timestamp=${1:-0}
    # Handle no timestamp as "never"
    [ "$timestamp" eq 0 ] 2>/dev/null && { printf 'never'; return; }
    # Find the delta between now and the given timestamp 
    now=$(date +%s); delta=$((now - ts))
    # Format at different resolutions
    if   [ $delta -lt 60 ]; then 
        printf 'just now'
    elif [ $delta -lt 3600 ]; then 
        printf '%dm ago' $((delta / 60))
    elif [ $delta -lt 86400 ];  then 
        printf '%dh ago' $((delta / 3600))
    elif [ $delta -lt 604800 ]; then 
        printf '%dd ago' $((delta / 86400))
    else                            
        printf '%dw ago' $((delta / 604800))
    fi
}
