#!/bin/sh
ROOT=$HOME/projects/finance


cmd_build() {
    cd $ROOT
    cargo build $*
}

cmd_run() {
    cd $ROOT
    cargo run $*
}

cmd_view() {
    cd $ROOT
    cargo run --bin finance -- $*
}

cmd_sync() {
    cd $ROOT
    cargo run --bin sync -- $*
}
