#!/bin/sh
ROOT=$HOME/untill/farmnet

use python-tooling
use work-management

_get_ssh_host() {
    case $1 in 
        seeder-0)    echo seeder.farmnet ;;
        structure-0) echo structure.0.farmnet ;;
        structure-1) echo structure.1.farmnet ;;
        harvester-0) echo harvester.farmnet ;;
        downlift-0)  echo downlift.0.farmnet ;;
    esac
}


_get_node_interlink_port() {
    case $1 in 
        seeder-0)      echo 5555 ;;
        structure-0)   echo 5556 ;;
        structure-1)   echo 5557 ;;
        harvester-0)   echo 5558 ;;
        downlift-0)    echo 5559 ;;
        water-room)    echo 5560 ;;
        water-room-a)  echo 5560 ;;
        water-room-b)  echo 5561 ;;
        water-room-c)  echo 5562 ;;
    esac
}

cmd_node() {
    cd "$ROOT"
    if [ -f "$ROOT/.env" ]; then
        source "$ROOT/.env"
    else
        echo "No .env file found: $ROOT/.env"
    fi
    cmd=$1; shift
    if [ -n "$1" ]; then
        NODE_PATH=$1; shift
    fi
    echo "Node: $NODE_PATH"
    REMOTE=`_get_ssh_host $NODE_PATH`
    echo "Host: $REMOTE"
    case $cmd in
        push)
            rsync -a --info=progress2 --delete-after \
            --exclude="*.pyc" \
            --include="/src/***" \
            --include="/scripts/***" \
            --include="/requirements.txt" \
            --exclude="*" \
            $ROOT/ $REMOTE:~/farmnet/
            ;;
        ssh|sftp) $cmd $REMOTE ;;
        test)
            interlink_routing_port=$(_get_node_interlink_port $NODE_PATH)
            echo "Interlink port: $interlink_routing_port"
            INTERLINK_ROUTING_PORT=$interlink_routing_port \
            NODE_PATH=$NODE_PATH \
            uv run src/main.py \
            ;;
        *) echo "Unknown command: node $cmd" ;;
    esac 
}

cmd_mmd() {
    cd "$ROOT"
    cmd=$1; shift
    case $cmd in
        serve)
            uv run tool/mmd/app.py --port 9000 ;;
        *) echo "Unknown command: mmd $cmd" ;;
    esac
}
