#!/bin/sh
ROOT=$HOME/untill/mlibs/db

cmd_publish() {
    cd "$ROOT"

    read -e -p "$(uv version) -> " version
    [[ -n $version ]] && uv version $version || version=$(uv version | cut -d' ' -f2)
    rm -rf dist/
    uv build --no-sources
    uv publish --index google
}

cmd_sh() {
    cd "$ROOT"
    pwd
    source ./.env.mongo
    uri="$MONGO_PROTOCOL://$MONGO_USER:$MONGO_PASSWORD@$MONGO_HOST"
    database="${1:-$MONGO_DATABASE}"
    [[ -n $1 ]] && shift
    mongosh "$uri/$database" $@
}
