#!/bin/sh
ROOT=$HOME/untill/mlibs/db

use gar-publish
use python-tooling

cmd_sh() {
    cd "$ROOT"
    pwd
    source ./.env.mongo
    uri="$MONGO_PROTOCOL://$MONGO_USER:$MONGO_PASSWORD@$MONGO_HOST"
    database="${1:-$MONGO_DATABASE}"
    [[ -n $1 ]] && shift
    mongosh "$uri/$database" $@
}
