#!/bin/sh
ROOT=$HOME/untill/printnet

_get_ssh_host() {
    case $1 in 
        cold-storage) echo cold-storage.printnet ;;
        receiving) echo receiving.printnet ;;
    esac
}


_get_ssh_host() {
    case $1 in 
        seeder-0)    echo seeder.farmnet ;;
        structure-0) echo structure.0.farmnet ;;
        structure-1) echo structure.1.farmnet ;;
        harvester-0) echo harvester.farmnet ;;
        downlift-0)  echo downlift.0.farmnet ;;
    esac
}
