#!/bin/sh
ROOT=$HOME/untill/printnet

use python-tooling

_get_ssh_host() {
    case $1 in 
        cold-storage) echo cold-storage.printnet ;;
        receiving) echo receiving.printnet ;;
    esac
}

cmd_node() {
    cd "$ROOT"
    if [ -f "$ROOT/.env" ]; then
        source "$ROOT/.env"
    else
        echo "No .env file found: $ROOT/.env"
    fi
    cmd=$1; shift
    NODE_NAME=$1; shift
    REMOTE=`_get_ssh_host $NODE_NAME`
    echo "Host: $REMOTE"
    case $cmd in
        push)
            rsync -a --info=progress2 --delete-after \
            --exclude="*.pyc" \
            --include="/src/***" \
            --include="/scripts/***" \
            --include="/requirements.txt" \
            --exclude="*" \
            $ROOT/ $REMOTE:~/farmnet/
            ;;
        ssh|sftp) $cmd $REMOTE ;;
        test)
            INTERLINK_PORT=$(_get_node_interlink_port $NODE_NAME)
            echo "Interlink port: $INTERLINK_PORT"
            while true; do
                INTERLINK_PORT=$INTERLINK_PORT \
                uv run src/main.py \
                --mode=test \
                --config="$NODE_NAME" \
                $@ -l PeerDiscovery=30 Uplink=30 Interlink=30
                sleep 2
            done
            ;;
        *) echo "Unknown command: node $cmd" ;;
    esac 
}
